ignored = ["github.com/huaweicloud/external-obs"]

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "0cf8f7e6ed1d2e3d47d02e3b6e559369af24d803"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.1"

[[constraint]]
  name = "gopkg.in/gcfg.v1"
  version = "1.2.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.1"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.9.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.1"

[[override]]
  name = "k8s.io/kubernetes"
  revision = "1872a800e9b9f17f08a7f6cc65015158de5681ef"

[[override]]
  name = "github.com/kubernetes-incubator/external-storage"
  revision = "92295a30e0ec7da80c41c1f50f9301f3adee4556"

[prune]
  go-tests = true
  unused-packages = true
