apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: obs-storage-class
provisioner: external.k8s.io/obs
parameters:
  accessKey: ak
  secretKey: sk
  storageClass: Standard
  bucketPolicy: private


---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: obs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: obs-storage-class

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/lib/www/html
        name: obs-data 
  volumes:
  - name: obs-data
    persistentVolumeClaim:
      claimName: obs-pvc 
      readOnly: false
