apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/lib/www/html
        name: obs-data 
  volumes:
  - name: obs-data
    persistentVolumeClaim:
      claimName: obs-pvc 
      readOnly: false
